/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin.Airliner;

import Business.Flight.Airliner;
import Business.Flight.AirlinerDirectory;
import Business.Flight.Airplane;
import Business.Flight.Fleet;
import Business.Flight.FlightScheduleCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhaoxi
 */
public class AddAirlinerJPanel extends javax.swing.JPanel {
    
    private JPanel rightJPanel;
    private AirlinerDirectory airlinerDir;
    
    /**
     * Creates new form AddAirlinerJPanel
     */
    public AddAirlinerJPanel(JPanel rightJPanel,AirlinerDirectory airlinerDir ) {
        initComponents();
        this.rightJPanel = rightJPanel;
        this.airlinerDir = airlinerDir;
    }
    
    private boolean inputStringCorrect(String s){
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
        Matcher m = p.matcher(s);
        boolean input = m.matches();
        return input;
    }
    
    public boolean inputFieldValid(){
        boolean inputFieldValid = true;
        
        if (txtAirliner.getText().equals("") || !inputStringCorrect(txtAirliner.getText())) {
            inputFieldValid = false;
        }
        
        for (int i = 0; i < airlinerDir.getAirlinerDirectory().size(); i++) {
            if (txtAirliner.getText().equals(airlinerDir.getAirlinerDirectory().get(i).getAirlinerName())) {
                inputFieldValid = false;
                break;
            }
        }
        return inputFieldValid;
    }
    
    public boolean airplaneSelected(){
        boolean airplaneSelected = false;
        
        if (btnBoeingB747.isSelected()) {
            airplaneSelected = true;
        }
        if (btnBoeingB767.isSelected()) {
            airplaneSelected = true;
        }
        if (btnBoeingB737.isSelected()) {
             airplaneSelected = true;
        }
        if (btnAirbusA380.isSelected()) {
             airplaneSelected = true;
        }
        if (btnAirbusA330.isSelected()) {
           airplaneSelected = true;
        }
        if (btnAirbusA319.isSelected()) {
            airplaneSelected = true;
        }
        return airplaneSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAirliner = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnBoeingB747 = new javax.swing.JRadioButton();
        btnBoeingB767 = new javax.swing.JRadioButton();
        btnBoeingB737 = new javax.swing.JRadioButton();
        btnAirbusA380 = new javax.swing.JRadioButton();
        btnAirbusA330 = new javax.swing.JRadioButton();
        btnAirbusA319 = new javax.swing.JRadioButton();

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Airliner");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Airplane");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Add New Airliner");

        btnBoeingB747.setText("BOEING-B747");

        btnBoeingB767.setText("BOEING-B767");

        btnBoeingB737.setText("BOEING-B737");

        btnAirbusA380.setText("AIRBUS-A380");

        btnAirbusA330.setText("AIRBUS-A330");

        btnAirbusA319.setText("AIRBUS-A319");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBoeingB747)
                            .addComponent(btnBoeingB767)
                            .addComponent(btnBoeingB737))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAirbusA380)
                            .addComponent(btnAirbusA330)
                            .addComponent(btnAirbusA319)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)
                        .addGap(27, 27, 27)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAirbusA380)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAirbusA330)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAirbusA319))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBoeingB747)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBoeingB767)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBoeingB737)))
                .addGap(32, 32, 32)
                .addComponent(btnAdd)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightJPanel.remove(this);
        Component [] componentArray = rightJPanel.getComponents();
        Component c = componentArray[componentArray.length-1];
        AirlinerMgrJPanel alm = (AirlinerMgrJPanel) c;
        alm.populateTable();
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String arilinerName = txtAirliner.getText();
        if (!inputFieldValid()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid airliner name!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            if (airplaneSelected()) {
                Fleet fleet = new Fleet();
                if (btnBoeingB747.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnBoeingB747.getText());
                    airplane.setCapacity(150);
                }
                if (btnBoeingB767.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnBoeingB767.getText());
                    airplane.setCapacity(150);
                }
                if (btnBoeingB737.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnBoeingB737.getText());
                    airplane.setCapacity(150);
                }
                if (btnAirbusA380.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnAirbusA380.getText());
                    airplane.setCapacity(150);
                }
                if (btnAirbusA330.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnAirbusA330.getText());
                    airplane.setCapacity(150);
                }
                if (btnAirbusA319.isSelected()) {
                    Airplane airplane = fleet.addAirplane();
                    airplane.setModel(btnAirbusA319.getText());
                    airplane.setCapacity(150);
                }

                Airliner airliner = airlinerDir.addAirliner();
                airliner.setAirlinerName(arilinerName);
                airliner.setFleet(fleet);
                airliner.setFlightScheduleCatalog(new FlightScheduleCatalog());

                JOptionPane.showMessageDialog(null, "Airliner successfully added!");

                txtAirliner.setText("");
                btnBoeingB747.setSelected(false);
                btnBoeingB767.setSelected(false);
                btnBoeingB737.setSelected(false);
                btnAirbusA380.setSelected(false);
                btnAirbusA330.setSelected(false);
                btnAirbusA319.setSelected(false);
            }
            else JOptionPane.showMessageDialog(null, "Please select at least one airplane!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton btnAirbusA319;
    private javax.swing.JRadioButton btnAirbusA330;
    private javax.swing.JRadioButton btnAirbusA380;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnBoeingB737;
    private javax.swing.JRadioButton btnBoeingB747;
    private javax.swing.JRadioButton btnBoeingB767;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAirliner;
    // End of variables declaration//GEN-END:variables
}
