/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin.Airliner;

/**
 *
 * @author zhaoxi
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    public ViewAirlinerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewAirlinerTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        airlinerLabel.setText("XXX Airliner");

        viewAirlinerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airliner", "Flight No.", "Airplane", "From", "To", "Date", "Departure", "Arrival", "Duration", "Capacity", "Remaining", "Status", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewAirlinerTable);
        if (viewAirlinerTable.getColumnModel().getColumnCount() > 0) {
            viewAirlinerTable.getColumnModel().getColumn(0).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(1).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(2).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(3).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(4).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(5).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(6).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(7).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(8).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(9).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(10).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(11).setResizable(false);
            viewAirlinerTable.getColumnModel().getColumn(12).setResizable(false);
        }

        btnBack.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(airlinerLabel)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(airlinerLabel)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnBack)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinerLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewAirlinerTable;
    // End of variables declaration//GEN-END:variables
}
