/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Admin.Flight;

/**
 *
 * @author zhaoxi
 */
public class FlightScheduleMgrJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FlightManagementJPanel
     */
    public FlightScheduleMgrJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        flightscheduleTable = new javax.swing.JTable();
        btnAddFlight = new javax.swing.JButton();
        btnUpdateFlight = new javax.swing.JButton();
        btnCancelFlight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        flightscheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight No.", "Airliner", "Airplane", "From", "To", "Date", "Departure", "Arrival", "Duration", "Capacity", "Remaining", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightscheduleTable);
        if (flightscheduleTable.getColumnModel().getColumnCount() > 0) {
            flightscheduleTable.getColumnModel().getColumn(0).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(1).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(2).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(3).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(4).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(4).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(5).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(5).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(6).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(7).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(8).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(8).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(9).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(9).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(10).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(10).setPreferredWidth(50);
            flightscheduleTable.getColumnModel().getColumn(11).setResizable(false);
            flightscheduleTable.getColumnModel().getColumn(11).setPreferredWidth(50);
        }

        btnAddFlight.setText("Add");

        btnUpdateFlight.setText("Update");
        btnUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFlightActionPerformed(evt);
            }
        });

        btnCancelFlight.setText("Cancel");

        btnBack.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateFlight)
                        .addGap(547, 547, 547)
                        .addComponent(btnCancelFlight))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(btnBack)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFlight)
                    .addComponent(btnUpdateFlight)
                    .addComponent(btnCancelFlight))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFlightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateFlightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelFlight;
    private javax.swing.JButton btnUpdateFlight;
    private javax.swing.JTable flightscheduleTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
