/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Flight.Airliner;
import Business.Flight.AirlinerDirectory;
import Business.Flight.FlightScheduleCatalog;
import UserInterface.Admin.Account.AccountMgrJPanel;
import UserInterface.Admin.Airliner.AirlinerMgrJPanel;
import UserInterface.Admin.Flight.FlightScheduleMgrJPanel;
import UserInterface.Admin.Order.OrderMgrJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author zhaoxi
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private AirlinerDirectory airlinerDir;
    private Airliner airliner;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel rightJPanel, AirlinerDirectory ad) {
        this.rightJPanel = rightJPanel;
        this.airlinerDir = ad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFlightscheduleMgr = new javax.swing.JButton();
        btnAirlinerMgr = new javax.swing.JButton();
        btnOrderMgr = new javax.swing.JButton();
        btnAccountMgr = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Admin Work Area");

        btnFlightscheduleMgr.setText("Flight Schedule Manager>>>");
        btnFlightscheduleMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightscheduleMgrActionPerformed(evt);
            }
        });

        btnAirlinerMgr.setText("Airliner Manager>>>");
        btnAirlinerMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinerMgrActionPerformed(evt);
            }
        });

        btnOrderMgr.setText("Order Manager>>>");
        btnOrderMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMgrActionPerformed(evt);
            }
        });

        btnAccountMgr.setText("Account Manager>>>");
        btnAccountMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountMgrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFlightscheduleMgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAirlinerMgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrderMgr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccountMgr, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(btnAirlinerMgr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFlightscheduleMgr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderMgr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccountMgr)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountMgrActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        rightJPanel.add(new AccountMgrJPanel(rightJPanel));
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnAccountMgrActionPerformed

    private void btnFlightscheduleMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightscheduleMgrActionPerformed
        // TODO add your handling code here:      
        FlightScheduleMgrJPanel fsm = new FlightScheduleMgrJPanel(rightJPanel,airlinerDir, airliner);
        rightJPanel.add("FlightScheduleMgrJPanel", fsm);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnFlightscheduleMgrActionPerformed

    private void btnAirlinerMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinerMgrActionPerformed
        // TODO add your handling code here:
        AirlinerMgrJPanel alm = new AirlinerMgrJPanel(rightJPanel,airlinerDir);
        rightJPanel.add("AirlinerMgr",alm);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnAirlinerMgrActionPerformed

    private void btnOrderMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMgrActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        rightJPanel.add(new OrderMgrJPanel(rightJPanel));
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnOrderMgrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountMgr;
    private javax.swing.JButton btnAirlinerMgr;
    private javax.swing.JButton btnFlightscheduleMgr;
    private javax.swing.JButton btnOrderMgr;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
